def get_cell_phenotype_id(dataset):
    if dataset == "Danenberg":
        cell_phenotype_id = {
            "CK^{med}ER^{lo}": 0,
            "ER^{hi}CXCL12^{+}": 1,
            "CK^{lo}ER^{lo}": 2,
            "Ep Ki67^{+}": 3,
            "CK^{lo}ER^{med}": 4,
            "Ep CD57^{+}": 5,
            "MHC I & II^{hi}": 6,
            "Basal": 7,
            "HER2^{+}": 8,
            "CK8-18^{hi}CXCL12^{hi}": 9,
            "CK^{+} CXCL12^{+}": 10,
            "CK8-18^{hi}ER^{lo}": 11,
            "CK8-18^{+} ER^{hi}": 12,
            "MHC I^{hi}CD57^{+}": 13,
            "MHC^{hi}CD15^{+}": 14,
            "CD15^{+}": 15,
            "CD4^{+} T cells & APCs": 16,
            "CD4^{+} T cells": 17,
            "CD8^{+} T cells": 18,
            "T_{Reg} & T_{Ex}": 19,
            "B cells": 20,
            "CD38^{+} lymphocytes": 21,
            "Macrophages": 22,
            "Granulocytes": 23,
            "Macrophages & granulocytes": 24,
            "CD57^{+}": 25,
            "Ki67^{+}": 26,
            "Endothelial": 27,
            "Fibroblasts": 28,
            "Fibroblasts FSP1^{+}": 29,
            "Myofibroblasts PDPN^{+}": 30,
            "Myofibroblasts": 31,
        }
    elif dataset == "Jackson":
        cell_phenotype_id = {
            "B cells ": 0,
            "B and T cells": 1,
            "T cells_1": 2,
            "Macrophages_1": 3,
            "T cells_2": 4,
            "Macrophages_2": 5,
            "Endothelial": 6,
            "Vimentin hi": 7,
            "small circular": 8,
            "small elongated": 9,
            "Fibronectin hi": 10,
            "larger elongated": 11,
            "SMA hi Vimentin": 12,
            "hypoxic": 13,
            "apoptotic": 14,
            "proliferative": 15,
            "p53 EGFR": 16,
            "Basal CK": 17,
            "CK7 CK hi Cadherin": 18,
            "CK7 CK": 19,
            "Epithelial low": 20,
            "CK low HR low": 21,
            "HR hi CK": 22,
            "CK HR": 23,
            "HR low CK": 24,
            "CK low HR hi p53": 25,
            "Myoepithalial": 26,
        }
    return cell_phenotype_id
